name       : hunspell-pt-br
version    : 2013.10.30
release    : 1
source     :
    - https://pt-br.libreoffice.org/assets/Uploads/PT-BR-Documents/VERO/ptBR-2013-10-30AOC-2.zip : ff20a997e4296b8b0bef2e6c19be437fa99442e7d7b3ea55cf9e0e1a6ab52a56
license    : 
    - LGPL-3.0-or-later
    - MPL-1.1
component  : spelling
summary    : Portuguese (Brazil) hunspell dictionary
description: |
    Brazilian Portuguese dictionary for hunspell.
install    : |
    install -Dm00644 pt_BR.{aff,dic} -t $installdir/usr/share/hunspell
